export default function Reports() {
  return (
    <div className="p-8">
      <h1 className="text-3xl font-bold mb-6 text-text-primary">Reports</h1>
      <p className="text-text-muted">Detailed incident and analysis reports generated by the system.</p>
    </div>
  )
}
